// ============================================================
// lib/main.dart
// ============================================================
// App entry point. Initializes Firebase and routes based on
// auth state: LoginScreen if logged out, HomeScreen if logged in.
// ============================================================

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart';

// ⚠️ This file is auto-generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli
//      flutterfire configure
// Then uncomment the import below:


import 'screens/login_screen.dart';
import 'screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Initialize Firebase ──────────────────────────────────
  // IMPORTANT: After running `flutterfire configure`, replace the line
  // below with: await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const ScamScannerApp());
}

class ScamScannerApp extends StatelessWidget {
  const ScamScannerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ScamScanner',
      debugShowCheckedModeBanner: false,

      // ── Global Theme ─────────────────────────────────────
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFE74C3C),
          brightness: Brightness.dark,
        ),
        useMaterial3: true,
        // Large base font size for elderly accessibility
        textTheme: const TextTheme(
          bodyLarge: TextStyle(fontSize: 20),
          bodyMedium: TextStyle(fontSize: 18),
          bodySmall: TextStyle(fontSize: 16),
          labelLarge: TextStyle(fontSize: 20),
          titleLarge: TextStyle(fontSize: 26, fontWeight: FontWeight.bold),
          titleMedium: TextStyle(fontSize: 22, fontWeight: FontWeight.w600),
          titleSmall: TextStyle(fontSize: 20),
          headlineMedium: TextStyle(fontSize: 28, fontWeight: FontWeight.bold),
        ),
        scaffoldBackgroundColor: const Color(0xFF1A1A2E),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF16213E),
          foregroundColor: Colors.white,
          elevation: 0,
          titleTextStyle: TextStyle(
            fontFamily: 'Roboto',
            fontSize: 24,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            minimumSize: const Size.fromHeight(60),
            textStyle: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: const Color(0xFF16213E),
          hintStyle: const TextStyle(fontSize: 18),
          contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 18),
          border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        ),
      ),

      // ── Auth-based Routing ───────────────────────────────
      // StreamBuilder listens to Firebase auth state changes.
      // User is routed to HomeScreen if authenticated, otherwise LoginScreen.
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          // Show loading while Firebase determines auth state
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              backgroundColor: Color(0xFF1A1A2E),
              body: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.shield_rounded, size: 80, color: Color(0xFFE74C3C)),
                    SizedBox(height: 20),
                    CircularProgressIndicator(color: Color(0xFFE74C3C)),
                    SizedBox(height: 16),
                    Text(
                      'ScamScanner',
                      style: TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.bold),
                    ),
                  ],
                ),
              ),
            );
          }

          // User is signed in → go to HomeScreen
          if (snapshot.hasData && snapshot.data != null) {
            return const HomeScreen();
          }

          // User is not signed in → go to LoginScreen
          return const LoginScreen();
        },
      ),
    );
  }
}