// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmTwlmdmLweSQMlHdJ4spOrarg002mxnc',
    appId: '1:689279764066:web:806a3c7a5f24ed3df5733b',
    messagingSenderId: '689279764066',
    projectId: 'scamscanner-368ad',
    authDomain: 'scamscanner-368ad.firebaseapp.com',
    storageBucket: 'scamscanner-368ad.firebasestorage.app',
    measurementId: 'G-FLK5XRQ1WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Hw9VPnonpFGNLmlJzXkgM1UrMGgJGBk',
    appId: '1:689279764066:android:142877c26d928220f5733b',
    messagingSenderId: '689279764066',
    projectId: 'scamscanner-368ad',
    storageBucket: 'scamscanner-368ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC47JNdaRz1oJKki-GLaUa2LdHiuoZFnXI',
    appId: '1:689279764066:ios:da61c2dc17bf32f1f5733b',
    messagingSenderId: '689279764066',
    projectId: 'scamscanner-368ad',
    storageBucket: 'scamscanner-368ad.firebasestorage.app',
    iosClientId: '689279764066-rghanvl15kdpop8n7ji4lsdkdaut5b25.apps.googleusercontent.com',
    iosBundleId: 'com.example.scamScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC47JNdaRz1oJKki-GLaUa2LdHiuoZFnXI',
    appId: '1:689279764066:ios:da61c2dc17bf32f1f5733b',
    messagingSenderId: '689279764066',
    projectId: 'scamscanner-368ad',
    storageBucket: 'scamscanner-368ad.firebasestorage.app',
    iosClientId: '689279764066-rghanvl15kdpop8n7ji4lsdkdaut5b25.apps.googleusercontent.com',
    iosBundleId: 'com.example.scamScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmTwlmdmLweSQMlHdJ4spOrarg002mxnc',
    appId: '1:689279764066:web:b3bb38b334fac0ecf5733b',
    messagingSenderId: '689279764066',
    projectId: 'scamscanner-368ad',
    authDomain: 'scamscanner-368ad.firebaseapp.com',
    storageBucket: 'scamscanner-368ad.firebasestorage.app',
    measurementId: 'G-JDF2K0QS7F',
  );
}
